"""Generate bend/exl3_tree_derive_proof.bend: exhaustive case analysis over the
5040 legal parent arrays; derive_refinement's legal leaves are closed top-level
lemmas. Usage: python3 -B bend/exl3_tree_derive_gen.py <repo root>."""

import sys
from itertools import product
from pathlib import Path

root = Path(sys.argv[1])
R7 = range(1, 8)
QQ = ", ".join(f"q{i}" for i in R7)
out = [
    """# Proofs of the derive laws of bend/exl3_tree_accept_laws.bend by exhaustive
# case analysis over the legal parent arrays (q_r < r: 7! = 5040 shapes);
# every illegal branch is refuted by the legality premise, every legal leaf is
# checked by evaluating both sides. The legal leaves of derive_refinement are
# closed lemmas (refine_<q1..q7>): the BendTT kernel evaluates a closed term
# with shared Data values, while under the case tree's open context the byte
# comparison stays lazy and unshared and runs out of fuel. Its illegal
# branches state q = r+1 + x as the successor chain the match leaves (not
# Nat.add), so they convert syntactically. No axioms, holes or answer tables.
# Generated by bend/exl3_tree_derive_gen.py; edit the generator, not this file.
import Base
import ./exl3_tree_accept.bend as Impl
import ./exl3_tree_accept_spec.bend as Spec
import ./exl3_tree_accept_laws.bend as Laws
import ./exl3_accept_proof.bend as ChainProof
"""
]

SHAPES = list(product(*[range(r) for r in R7]))
assert len(SHAPES) == 5040


def refine_goal(v):
    return f"{{Impl.bytes(Impl.derive({', '.join(v)})) == Spec.derive([{', '.join(v)}]) : List<&2, Nat>}}"


def leaves(prefix, goal_of):
    lines = []
    for shape in SHAPES:
        name = prefix + "".join(str(q) for q in shape)
        lines.append(f"def {name}() -> {goal_of([f'{q}n' for q in shape])}:")
        lines.append("  {==}")
        lines.append("")
    return "\n".join(lines)


def gen(name, goal_of, prefix=None):
    """goal_of(values) -> goal text; values: list of 7 expressions. With a
    prefix, legal leaves call the closed lemmas prefix<digits>()."""
    lines = [f"def {name}({QQ}, legal):"]

    def rec(r, vals, ind):
        if r == 8:
            lines.append(
                f"{ind}{prefix}{''.join(v[:-1] for v in vals)}()"
                if prefix
                else f"{ind}{{==}}"
            )
            return
        var = f"q{r}"
        for v in range(r):
            lines.append(f"{ind}match {var}:")
            lines.append(f"{ind}  case 0n:")
            rec(r + 1, vals + [f"{v}n"], ind + "    ")
            nv = f"{var}_{v}"
            lines.append(f"{ind}  case 1n+{nv}:")
            ind += "    "
            var = nv
        rest = [f"q{i}" for i in range(r + 1, 8)]
        lines.append(f"{ind}match {var}:")
        lines.append(f"{ind}  case 0n:")
        lines.append(
            f"{ind}    Empty.absurd({goal_of(vals + [f'{r}n'] + rest)}, ChainProof.false_true(legal))"
        )
        lines.append(f"{ind}  case 1n+{var}_x:")
        big = f"{r + 1}n+{var}_x" if prefix else f"Nat.add({r + 1}n, {var}_x)"
        lines.append(
            f"{ind}    Empty.absurd({goal_of(vals + [big] + rest)}, ChainProof.false_true(legal))"
        )

    rec(1, [], "  ")
    return "\n".join(lines) + "\n"


out.append(
    "# Legal leaves of derive_refinement: the executed leaf's bytes are the reference's."
)
out.append(leaves("refine_", refine_goal))
out.append(gen("Laws.derive_refinement", refine_goal, "refine_"))
out.append(
    gen(
        "Laws.derive_sound",
        lambda v: (
            f"{{Spec.sound([{', '.join(v)}], Spec.derive([{', '.join(v)}])) == True{{}} : Bool}}"
        ),
    )
)
out.append("""def Laws.sound_rejects():
  ({==}, {==}, {==})
""")
(root / "bend/exl3_tree_derive_proof.bend").write_text("\n".join(out))
